### ISSUE TITLE
Cannot change shortcut back to ⌃⌥⌘T

### ISSUE THREAD

**Issue by YourMJK** [r-thomson/Nightfall#35] opened 2024-08-13 23:32 UTC
Certain shortcuts seem to get "eaten up" and thus cannot be used to configure Nightfall's shortcut in the settings window.

One of them is ⌃⌥⌘A, another one is the default ⌃⌥⌘T.  
So after changing the shortcut once, you can't change it back to the default.

**Comment by r-thomson** [comment] 2024-08-14 01:39
That’s interesting, I’m not able to reproduce this on my end for either of the shortcuts you provided.

Do you possibly have some other application using that shortcut? I’d also appreciate your macOS version.

**Comment by YourMJK** [comment] 2024-08-14 08:34
Sorry, forgot to mention the version, that's on macOS Sonoma 14.6.1.  
This happens with no other apps in the foreground or (visibly) open. 

I'm not aware that the shortcut is used by a different process. Is there a way to find that out?

I'm not sure if that's relevant but my locale is set to German (I think some default shortcuts are locale-dependent).

Also, I have Keyboard Maestro 9 installed but there are not hot key triggers registered for those shortcuts.

**Comment by YourMJK** [comment] 2024-08-14 14:47
German locale doesn't seem to be the issue, the shortcuts work fine on a different MacBook with macOS 13 (and without Keyboard Maestro).

**Comment by r-thomson** [comment] 2024-08-14 15:23
Never used Keyboard Maestro so I can't say for sure if that's got an effect. Please let me know what else you discover.

If you're just looking for a temporary workaround, try running this shell command:

```sh
defaults delete net.ryanthomson.Nightfall KeyboardShortcuts_ToggleDarkMode
killall Nightfall
```

**Comment by r-thomson** [comment] 2024-08-24 16:27
Closing: can not reproduce

**Closed as not planned by r-thomson** 2024-08-24 16:27 UTC

**Comment by YourMJK** [comment] 2024-08-24 18:24
Quitting Keyboard Maestro engine and every other application, changing language & region to EN-UK and restarting didn't fix the issue, still persists for me in macOS Sonoma 14.6.1 on MacBook Pro M1 with German QWERTZ keyboard layout.

Using ⌃⌥⌘ with these keys doesn't work to set as a shortcut (**but they do by adding shift**, i.e. ⌃⌥⇧⌘T works!):
`T, P, A, S, K, L, C, COMMA, DOT`

All the other keys work using this combination, I checked them.

**Comment by r-thomson** [comment] 2024-08-26 13:02
> Quitting Keyboard Maestro engine and every other application, changing language & region to EN-UK and restarting didn't fix the issue, still persists for me in macOS Sonoma 14.6.1 on MacBook Pro M1 with German QWERTZ keyboard layout.
> 
> Using ⌃⌥⌘ with these keys doesn't work to set as a shortcut (**but they do by adding shift**, i.e. ⌃⌥⇧⌘T works!): `T, P, A, S, K, L, C, COMMA, DOT`
> 
> All the other keys work using this combination, I checked them.

Thanks, doesn't happen on any of my Macs, but I'll see if I can reproduce on a VM when I have the time.
