### ISSUE TITLE
Can't be opened on macOS Monterey 12.0.1

### ISSUE THREAD

**Issue by dumazy** [r-thomson/Nightfall#13] opened 2021-10-30 09:39 UTC
After upgrading to macOS Monterey 12.0.1 Nightfall can no longer be opened.
The following pop-ups show up when trying:

> The application "Nightfall" can't be opened

![nightfall-cant-be-opened](https://user-images.githubusercontent.com/2174500/139527947-29499ed9-20a2-4a6e-a455-023f1cd45e33.png)

> "Nightfall" will damage your computer. You should move it to the Bin.

![nightfall-will-damage](https://user-images.githubusercontent.com/2174500/139527938-bbf9be15-abe7-4a53-a9b8-25a35206b009.png)

**Comment by r-thomson** [comment] 2021-10-30 16:43
Thanks for reporting this.

I was able to reproduce this issue with one of my Macs running Catalina, but not from a machine running Monterey. I'll release an updated version as soon as I'm able to identify the cause of the issue.

**Comment by jensenharris** [comment] 2021-10-30 21:01
Yes, I can no longer open this either—tried installing through Brew and direct download.

Sounds like the app has been flagged as malware by Apple.

**Comment by r-thomson** [comment] 2021-10-30 23:24
It seems to be a code signing problem— the `codesign` utility is showing the error `CSSMERR_TP_CERT_REVOKED`.

~Interestingly, it seems to only affect the Intel version of the app.~ This is incorrect, both architectures are showing this error

**Comment by r-thomson** [comment] 2021-10-30 23:59
I've adjusted the app's signing here, please let me know if this resolves the problem.

[Nightfall.zip](https://github.com/r-thomson/Nightfall/files/7447798/Nightfall.zip)

**Comment by jensenharris** [comment] 2021-10-31 05:06
> I've adjusted the app's signing here, please let me know if this resolves the problem.
> 
> [Nightfall.zip](https://github.com/r-thomson/Nightfall/files/7447798/Nightfall.zip)

Yes, this version does fix this error for me. Thank you!

**Comment by r-thomson** [comment] 2021-10-31 16:40
Should be fixed in [version 2.1.3](https://github.com/r-thomson/Nightfall/releases/tag/v2.1.3)

**Closed as completed by r-thomson** 2021-10-31 16:40 UTC
Labels: bug

**Comment by PkAIR** [comment] 2021-10-31 19:14
@r-thomson faced same issue with version 2.1.3 on intel mac with catalina.

**Comment by rodchristiansen** [comment] 2021-11-07 17:58
Version 2.1.3 still has signing issues. Gatekeeper is rejecting it because its considered an Ad-hoc signature. 
<img width="323" alt="Screen Shot 2021-11-07 at 09 56 57" src="https://user-images.githubusercontent.com/7052526/140656221-c36f094c-05b7-42e8-b994-a86209d70e58.png">

**Comment by r-thomson** [comment] 2021-11-07 18:12
> Version 2.1.3 still has signing issues. Gatekeeper is rejecting it because its considered an Ad-hoc signature.

Gatekeeper will never accept this app because I don't have a Developer ID to sign with (it's not worth the $100/year for me just to distribute a free app).

If there's a better way to configure the signing, please let me know.

**Comment by akoss** [comment] 2021-11-08 15:26
Indeed it won't open on MacOS 12.0.1 by default: 
<img width="372" alt="Screenshot 2021-11-08 at 15 21 53" src="https://user-images.githubusercontent.com/6537461/140769057-af4d737a-fd90-4f10-b3db-b7290cda9621.png">

However, right-clicking the .app and selecting `Open` now reveals the usual option to override Gatekeeper. I also had to re-grant screen recording permission. 

<img width="372" alt="Screenshot 2021-11-08 at 15 22 07" src="https://user-images.githubusercontent.com/6537461/140769089-0b738817-2709-4e56-91eb-bf209fc80483.png">

Thanks Ryan, I love this app!
