### ISSUE TITLE
Flagged as Malware

### ISSUE THREAD

**Issue by braebo** [r-thomson/Nightfall#15] opened 2021-11-02 17:38 UTC
I've used Nightfall for a long time- love it!

Today I got this popup when trying to start it:
<img width="351" alt="Screenshot 2021-11-02 at 1 35 32 PM" src="https://user-images.githubusercontent.com/55504972/139916839-c6693541-c5a4-4499-9075-3fe54f22e729.png">

If I press "Cancel", it just returns after a few seconds.

System Preferences / Security doesn't show the usual dialog / allow button.

Any insight into what this is about?  I'm on Big Sur via 2019/2020 MBP

**Comment by r-thomson** [comment] 2021-11-02 18:01
AFAIK, this is caused by a problem with the signing certificate used when building the app. This issue should be fixed in [version 2.1.3](https://github.com/r-thomson/Nightfall/releases/tag/v2.1.3). You should move your currently installed version to the trash.

See also: #13

**Closed as completed by r-thomson** 2021-11-02 18:01 UTC
