### ISSUE TITLE
Suggestion: Allow Ability to Hide Menubar

### ISSUE THREAD

**Issue by snbbdx** [r-thomson/Nightfall#12] opened 2021-09-17 09:26 UTC
I hope to increase the option of hiding menu application icons, and I am usually used to shortcut keys，Hope to adopt the opinions, thank you！

**Comment by r-thomson** [comment] 2021-09-17 13:08
Duplicate of https://github.com/r-thomson/Nightfall/issues/10

**Closed as completed by r-thomson** 2021-09-17 13:08 UTC
